jgm/pandoc-types

pandoc-types.cabal

Allow `pandoc-types` to build with the latest version of `aeson` (0.9.0.1).
Note that [`pandoc` itself](https://github.com/jgm/pandoc/blob/d9e5d9fe068931a7244a6b72e33c4a7dbacbe7ef/pandoc.cabal#L262) also has an out-of-date `aeson` dependency.

Bump aeson upper version bounds

---

Text/Pandoc/Arbitrary.hs
Text/Pandoc/Definition.hs
pandoc-types.cabal
test/test-pandoc-types.hs

1. This adds manual ToJSON and FromJSON instances, instead of the generic-derivied instances we had previously used. This should keep the format stable, regardless of  changes in aeson. Empirically, it also adds a small speedup in encoding and decoding.
2. This updates the pandoc json format. There are three main changes:
1. The toplevel format is now
~~~{.json}
{
"pandoc-api-version": [1,7,1],
"meta": [meta*],
"blocks": [blocks*]
}
~~~
where `meta` and `blocks` are individual `Meta` and `Block` elements. Note that this means that the   toplevel is now an object, and that `meta` elements are no longer under an `unMeta` key.
2. The "pandoc-api-version" tracks the pandoc-types version. If the major and minor versions (the 0th and 1st elements of the array) do not match, decoding in pandoc …

Reimplement ToJSON / FromJSON instances, and update format

---

pandoc-types.cabal
test/test-pandoc-types.hs

Previously we had just done round-trip tests, but that can hide a
mistake if the encoder and decoder are making the same mistake (or if
the encoder makes a mistake that the decoder ignores). This tests each
pandoc entity against a specific JSON string. There is some redundancy
because of the recursive nature of pandoc types, but testing each type
individually will help us pinpoint problems.
Note that this uses a simple quasiquoting library (strings-qq) to avoid
escaping every quote in a JSON string.

Add explicit unit tests for encoding and decoding.

---

Text/Pandoc/Arbitrary.hs
test/test-pandoc-types.hs

LineBlocks are generated with an open-ended number of lines and up to three
inline elements per line.

Add tests for LineBlock elements

---

.gitignore
Text/Pandoc/Walk.hs
pandoc-types.cabal

The implementations for `walk` and `walkM` are very similar, so a default method is provided which implements the former in terms of the latter. This change should not affect performance, as the `Identity` functor, which is used in the default definition, is a newtype that should be eliminated at compile time.
GHC 7.8 (i.e., base <= 4.7) does not provide the `Data.Functor.Identity` type, so we use the one included in the transformers library. The transformers library was already an indirect dependency due to Aeson, so while requiring it is ugly, it does not cause additional code to be included.

Default implementation for walk

---

Text/Pandoc/Walk.hs

The functions defined in the Walk module are relatively simple while
being called recursively on possibly long documents. It hence seems
sensible to force optimizations for this module, as the benefits likely
outweigh the additional compile time.
This also reduces the performance cost of having a default
implementation for `walk` based on `walkM`.

Force optimizations when compiling Walk module

---

Text/Pandoc/Walk.hs
test/test-pandoc-types.hs

Add Walkable instances for lists of Inlines and lists of Blocks.  This is a prerequisite for jgm/pandoc#3926.

Walkable element lists

---

Text/Pandoc/Arbitrary.hs

SoftBreak is considered to be a space, while LineBreak is not,
similarly to how trimInlines handles it

Text.Pandoc.Arbitrary: generate SoftBreaks and LineBreaks

---

Text/Pandoc/Arbitrary.hs
Text/Pandoc/Definition.hs
Text/Pandoc/Walk.hs

As a hackage trustee, I've made revisions to versions 1.17.4.2 and 1.17.4.1 to increase their base lower bounds to `>= 4.8` and `>=4.9` respectively.
This patch will make pandoc-types compile as far back as GHC 7.4

Add extra imports to fix build on older GHCs

---

pandoc-types.cabal

The URL currently listed as the homepage just redirects to `pandoc.org`.

Change homepage to pandoc.org

---

Text/Pandoc/Walk.hs

The `walk*M` and `query*` functions are helpful when defining new
`Walkable` instances.

Walk: export walk and query helpers

---

Text/Pandoc/Legacy/Definition.hs

These should stop the incomplete pattern match errors.

Add COMPLETE pragmas to the pattern definitions

---

Text/Pandoc/Arbitrary.hs
Text/Pandoc/Builder.hs
Text/Pandoc/Definition.hs
Text/Pandoc/Walk.hs
pandoc-types.cabal
test/test-pandoc-types.hs

The initial implementation of issue #65. Other differences:
- The `Builder.table` and `Builder.simpleTable` have been adapted to the new type but have not had their signature or behaviour changed.
- The `Arbitrary` behaviour for tables is now different. Most notably, the instances do not produce normalized tables.
- The `Legacy.Definition` and `Legacy.Builder` modules are now not exposed. Would you like me to update them in some way, or remove them?
- There are `ToJSON` and `FromJSON` instances for `Row`, `Cell`, and `Caption`, all tagged. I checked the JSON output of the serialization test case and it seemed fine, so I updated the [expected bytestring](https://github.com/jgm/pandoc-types/compare/master...despresc:better-tables#diff-01f4ffe52cf097ab9ff89eebce394c86R369) in the test.
- …

Better tables

---

src/Text/Pandoc/Builder.hs
src/Text/Pandoc/Definition.hs
test/test-pandoc-types.hs

Right now the `table` builder enforces the `RowHeadColumns` boundary in the intermediate head of a `TableBody`. That means that a `TableBody` is currently supposed to look like
```
+-----------------------+--------------+
|  Head above row head  | Rest of head |
+-----------------------+--------------+
|        Row head       |    Row body  |
+-----------------------+--------------+
```
so if there were a cell in the top left whose width exceeded the `RowHeadColumns`, it would be shrunk to fit. I think this is a leftover of the original design of the new `Table` that had no intermediate tables at all; in that case the model above is actually how tables normally behave. But tables with intermediate sub-tables frequently have headings that stretch across the entire table (an …

Change the table builder to permit looser intermediate table heads

---

src/Text/Pandoc/Arbitrary.hs

Use null in Arbitrary

---

src/Text/Pandoc/Definition.hs

The documentation stated that the ColWidth represented the width
of the column as a fraction of the table width when in represents
a percentage of the page width.

Fix incorrect table ColWidth documentation

---

pandoc-types.cabal

`cabal build --enable-tests --constrain 'bytestring == 0.11.1.0' && cabal test --enable-tests --constrain 'bytestring == 0.11.1.0'` passes.

Allow bytestring 0.11

---

src/Text/Pandoc/Builder.hs
src/Text/Pandoc/Definition.hs
test/test-pandoc-types.hs

Technically not API-Change ?
The first change part of #90
To address some of the issues with the previous handling of figures, we introduced, along with some helper functions, the `SimpleFigure` [pattern synonym](https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/pattern_synonyms.html)
```haskell
-- | Constructor for a figure with a single image.
--
-- It can be used to construct a figure:
--
-- >>> SimpleFigure nullAttr [] (T.pack "", T.pack "title")
-- Para [Image ("",[],[]) [] ("","fig:title")]
--
--
-- It can be used to pattern match:
--
-- >>> let img = Para [Image undefined undefined (undefined, T.pack "title")]
-- >>> case img of { SimpleFigure _ _ _ -> True; _ -> False }
-- False
-- >>> let fig = Para [Image undefined undefined (undefined, T.pack "fig:title")]
-- >>> case fig …
```

Add the SimpleFigure bidirectional pattern synonym.

---

src/Text/Pandoc/JSON.hs

Neither `Walkable Meta Pandoc` nor `Walkable MetaValue Pandoc` instances exist, so these types cannot be used with `ToJSONFilter`.
I grepped the source to check if there are any instances that I am not importing, and I did not find any.
I wrote a simple program to confirm that I am not missing something, and I indeed get errors for both types.
```haskell
{-# LANGUAGE TypeApplications #-}
module Main (main) where
import qualified Text.Pandoc.JSON as Pandoc
mainMeta :: IO ()
mainMeta = Pandoc.toJSONFilter $ id @Pandoc.Meta
mainMetaValue :: IO ()
mainMetaValue = Pandoc.toJSONFilter $ id @Pandoc.MetaValue
main :: IO ()
main = undefined
```
```
/path/to/Meta.hs:8:12: error:
• No instance for (Text.Pandoc.Walk.Walkable
Pandoc.Meta Pandoc.Pandoc)
arising from a use of ‘Pandoc.toJSONFilter’
• In …
```

Update ToJSONFilter docs: remove Meta, MetaValue

---

src/Text/Pandoc/JSON.hs
src/Text/Pandoc/Walk.hs
test/test-pandoc-types.hs

I implemented the following instances, allowing `ToJSONFilter` to work with `Meta` and `MetaValue`, as suggested in #95.
* `Walkable Meta Pandoc`
* `Walkable MetaValue Pandoc`
Notes:
* The `Walkable Meta Pandoc` instance does not need to recurse because `Meta` is only used in `Pandoc`.  There is no `[Meta]` instance because there is only a single `Meta` value.
* The `Walkable MetaValue Pandoc` instance makes use of new `Walkable MetaValue Meta` and `Walkable MetaValue MetaValue` instances.  These instance implementations map over containers directly; there is no `[MetaValue]` instance because `MetaValue` is also used as `Meta` and `MetaMap` map values.
Please let me know if there are any issues or formatting inconsistencies that you would like me to correct.  You are of course welcome to …

Add Walkable Meta(Value) Pandoc instances

---

src/Text/Pandoc/Arbitrary.hs
src/Text/Pandoc/Builder.hs
src/Text/Pandoc/Definition.hs
src/Text/Pandoc/Walk.hs
test/test-pandoc-types.hs

The new Figure block represents a figure with attributes, caption,
and arbitrary block content.
This combines code by @despresc and @argent0.

[API change] Add `Figure` block constructor

---

src/Text/Pandoc/JSON.hs

work with any MonadIO fixing #104

---

src/Text/Pandoc/Arbitrary.hs
src/Text/Pandoc/Definition.hs
src/Text/Pandoc/Walk.hs
test/test-pandoc-types.hs

Remove Null constructor from Block.

---

pandoc-types.cabal
test/Data/String/QQ.hs

This pull request replaces the dependency on the string-qq package with a compatible module. Depending on string-qq causes the transitive dependency graph to require `text >=1.2 && <1.3`. Removing this dependency will allow building with newer versions of `text` (tested with text-2.0.1). Given the very small size and limited use of `string-qq`, removing a dependency here seems like a win.

Remove string qq dependency
